name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # GitHub 저장소를 체크아웃
      - uses: actions/checkout@v4

      # Python 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 필요 시 의존성 패키지 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Lab10.py 파일 실행
      - name: Run Lab10.py
        run: python Lab10.py 100  # 필요한 경우, 원하는 인자를 전달
